# coding: utf-8

# flake8: noqa
"""
    Book Management API

    API dùng để quản lý sách (CRUD, tìm kiếm, cập nhật...)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.book import Book
from openapi_client.models.book_update import BookUpdate

