# coding: utf-8

"""
    Book Management API

    API dùng để quản lý sách (CRUD, tìm kiếm, cập nhật...)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_update import BookUpdate

class TestBookUpdate(unittest.TestCase):
    """BookUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookUpdate:
        """Test BookUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookUpdate`
        """
        model = BookUpdate()
        if include_optional:
            return BookUpdate(
                title = '',
                author = '',
                price = 1.337
            )
        else:
            return BookUpdate(
        )
        """

    def testBookUpdate(self):
        """Test BookUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
